services:
  - type: web
    name: telegram-quiz-bot
    env: python
    buildCommand: pip install -r railway_requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    autoDeploy: true